Repository fpclass/perpetual-haskelling-initiative, pull requests merged in 2020-05, with the labels that each got.

#3 Add GitHub Actions CI
  .github/workflows/haskell.yml
Labels: enhancement

#10 Add FromJSON/ToJSON instances to basic types
  package.yaml
  perpetual-haskelling-initiative.cabal
  src/Purestone/Card.hs
  src/Purestone/JSON.hs
  src/Purestone/Language/Program.hs
  src/Purestone/Paradigm.hs
Labels: enhancement

#9 Basic game types
  package.yaml
  perpetual-haskelling-initiative.cabal
  src/Purestone.hs
  src/Purestone/Card.hs
  src/Purestone/Hand.hs
  src/Purestone/JSON.hs
  src/Purestone/Language/Program.hs
  src/Purestone/Paradigm.hs
Labels: enhancement, good first issue

#7 Add terminal UI
  app/Main.hs
  package.yaml
  perpetual-haskelling-initiative.cabal
  src/Purestone/Paradigm.hs
Labels: enhancement

#12 Feature/readme
  AUTHORS
  README.md
Labels: documentation, help wanted

#16 Remove .cabal file
  .gitignore
  perpetual-haskelling-initiative.cabal
Labels: enhancement

#18 Add API server
  package.yaml
  server/Main.hs
  src/Purestone/Board.hs
  src/Purestone/Game.hs
  src/Purestone/JSON.hs
  src/Purestone/Player.hs
  src/Purestone/Server/App.hs
  src/Purestone/Server/ConnectResponse.hs
  src/Purestone/Server/GameState.hs
  src/Purestone/Server/GetState.hs
  src/Purestone/Server/MakeMove.hs
  src/Purestone/Server/Sanitise.hs
  src/Purestone/Server/Util.hs
Labels: enhancement
